spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/bookStore
    username: root
    password: 1q2w3e4r
  application:
    name: basic-security
    # ???????? ?? ???? ?????
  jpa:
    hibernate:
      ddl-auto: create
      # ?? ?? ???? create? ??? ?? ? ??? update? ???
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  jwt:
    expiration_time: 86400000
    secret:
      key: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa
      # ??? jwt ??? ? ?? ???? ???? ???? ??? ??
server:
  port: 9090